language: node_js
node_js:
  - '0.10'
  - '0.11'
notifications:
  email: false
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/f1d48355795bf25a8f9a
    on_success: change
    on_failure: always
    on_start: never
after_success: cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js
